# Generated by Django 3.2.7 on 2021-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section_production_rate',
            old_name='max_amount_of_section_product_produced_per_hour',
            new_name='max_ideal_amount_of_section_product_produced_per_hour',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
