# Generated by Django 3.2.7 on 2021-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_cost_per_part_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_equip_size_reqs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_equipment_ops_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_labour_ops_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_misc_ops_costs_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_misc_size_reqs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_number_of_parts_produced_per_hour',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_operating_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_size_required_m2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='availabletechnology',
            name='total_start_up_cost_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='area_required_per_Equipmentunit_m2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='number_of_equipment_units_needed',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='parts_replacement_cost_per_equipmentUnit_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='resources_cost_per_equipmentUnit_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_area_required_for_all_units_m2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_parts_replacement_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_resources_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_running_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment_maintenance_cost',
            name='part_replacement_cost_per_unit_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment_resource_cost',
            name='cost_per_equipmentUnit_per_hour_for_this_resource_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment_resource_cost',
            name='cost_per_single_unit_resource_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='equipment_resource_cost',
            name='resource_quantity_needed_per_EquipmentUnit_per_hour',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='event_cost_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='labour_plantoperatingcost',
            name='number_of_labourers_required_for_this_role',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='labour_plantoperatingcost',
            name='safety_risk_cost_per_hour_per_labourer_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='labour_plantoperatingcost',
            name='salary_per_hour_per_labourer_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='labour_plantoperatingcost',
            name='total_labourCost_per_hour_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='miscellaneous_area_requirement',
            name='area_allotment_m2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='miscellaneous_plantinstallationcost',
            name='cost_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='miscellaneous_plantoperatingcost',
            name='per_hour_cost_Rs',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
    ]
