# Generated by Django 3.2.7 on 2021-09-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='maintenance_down_time_fraction_per_equipmentUnit_per_hour',
            new_name='maintenance_down_time_fractions_per_equipmentUnit_per_hour',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='total_maintenance_down_time_fraction_per_hour',
            new_name='total_maintenance_down_time_fractions_per_hour',
        ),
        migrations.RenameField(
            model_name='equipment_maintenance_cost',
            old_name='equipment_replacement_cost_per_unit_per_hour_Rs',
            new_name='part_replacement_cost_per_unit_per_hour_Rs',
        ),
    ]
