# Generated by Django 3.2.7 on 2021-09-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section_production_rate',
            old_name='product_name',
            new_name='section_name',
        ),
    ]
