# Generated by Django 3.2.7 on 2021-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0002_auto_20210929_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletechnology',
            name='total_equip_size_reqs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='availabletechnology',
            name='total_equipment_ops_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='availabletechnology',
            name='total_labour_ops_cost_per_hour_Rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='availabletechnology',
            name='total_misc_ops_costs_per_hour_Rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='availabletechnology',
            name='total_misc_size_reqs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
