# Generated by Django 3.2.7 on 2021-09-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0002_auto_20210926_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_production_rate',
            name='labour_role_needed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_sections', to='feasibility_calculator.labour_plantoperatingcost'),
        ),
    ]
