# Generated by Django 3.2.7 on 2021-09-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0003_alter_section_production_rate_labour_role_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='total_maintenance_down_time_fractions_per_hour',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
