# Generated by Django 3.2.7 on 2021-09-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_calculator', '0005_alter_equipment_number_of_equipment_units_needed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment_resource_cost',
            old_name='resource_quantity_neede_per_EquipmentUnit_per_hour',
            new_name='resource_quantity_needed_per_EquipmentUnit_per_hour',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='production_hours_per_month',
            new_name='production_hours_per_day',
        ),
    ]
