# Generated by Django 3.2.7 on 2021-12-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_number', models.IntegerField(default=0)),
                ('process_name', models.CharField(max_length=100)),
                ('immersion_time_mins', models.IntegerField(default=0)),
                ('is_wait_type_tank', models.BooleanField(default=False)),
                ('max_wait_time_mins', models.IntegerField(default=0)),
                ('tank_type_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '             1. tanks',
            },
        ),
    ]
