# Generated by Django 3.2.7 on 2021-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroplating_automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='immersion_time_mins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tank',
            name='max_wait_time_mins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
